# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.1
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_DB
      value: gesis
    - name: POSTGRES_PASSWORD
      value: "123"
    - name: POSTGRES_USER
      value: gesis
    image: docker.io/library/postgres:17.4-alpine3.21
    name: db
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-data-pvc
  volumes:
  - hostPath:
      # This is the path in the host machine running Kubernetes or Podman.
      # When using WSL2, the Windows C disk is mounted into /mnt/c.
      path: /mnt/c/Users/costadre/Downloads/postgresql
      type: Directory
    name: db-data-pvc
