variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

build documentation:
  image: docker-private.gesis.intra/rse/docker/images/sphinx-doc:2.3.0
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - source/**/*
  script:
    - make html
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
  dependencies:
    - build documentation
  script:
    - mkdir -p public
    - mv build/html/* public
  artifacts:
    paths:
      - public
