apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-secret0
  name: nginx-secret0
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    image: docker.io/library/nginx:alpine
    name: nginx
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-secret
  volumes:
  - secret:
      # Provide the name of the ConfigMap you want to mount.
      secretName: html
    name: nginx-secret
